//! `bi gen struct` over the sample pair, in every language: a unit and a
//! `bi_types` with every builtin, ids from the data, the sample mapping
//! changing nothing. Text only — nothing here compiles what was written.

use std::path::{Path, PathBuf};

use bi::codegen::structs::{Lang, Request, generate};
use bi::props::sample;

fn request(lang: Lang, mapping: bool) -> Request {
    Request {
        lang,
        pkg: Some("gen.sample".into()),
        inputs: vec![
            (PathBuf::from("game.bischema"), sample::SCHEMA.to_string()),
            (PathBuf::from("level1.bidata"), sample::DATA.to_string()),
        ],
        mappings: if mapping {
            vec![(PathBuf::from("game.bimapping"), sample::MAPPING.to_string())]
        } else {
            Vec::new()
        },
        dir_name: "out".into(),
    }
}

fn no_read(p: &Path) -> Result<String, String> {
    Err(format!("unexpected read of {}", p.display()))
}

#[test]
fn every_language_writes_the_sample_and_its_support_file() {
    for lang in Lang::ALL {
        let out = generate(&request(lang, false), &mut no_read)
            .unwrap_or_else(|e| panic!("{lang:?}: {e:?}"));
        let paths: Vec<String> = out.files.iter().map(|f| f.path.display().to_string()).collect();
        assert_eq!(
            paths,
            [format!("game.{}", lang.ext()), format!("bi_types.{}", lang.ext())],
            "{lang:?}"
        );
        let unit = &out.files[0].text;
        let support = &out.files[1].text;
        assert!(unit.contains("generated by `bi gen struct` from game.bischema"), "{lang:?}");
        // Every builtin the sample uses is in the support file.
        let names: &[&str] = match lang {
            Lang::C => &[
                "bi_rgb",
                "bi_rgba",
                "bi_curve_point",
                "bi_curve",
                "bi_gradient_stop",
                "bi_gradient",
                "bi_ref",
            ],
            Lang::Cpp => &[
                "struct Rgb",
                "struct Rgba",
                "struct CurvePoint",
                "struct Curve",
                "struct GradientStop",
                "struct Gradient",
                "struct Ref",
            ],
            Lang::Go => &[
                "type Rgb struct",
                "type Rgba struct",
                "type CurvePoint struct",
                "type Curve struct",
                "type GradientStop struct",
                "type Gradient struct",
                "type Ref[",
            ],
            Lang::Rust => &[
                "pub struct Rgb",
                "pub struct Rgba",
                "pub struct CurvePoint",
                "pub struct Curve",
                "pub struct GradientStop",
                "pub struct Gradient",
                "pub struct Ref<T>",
            ],
            Lang::C3 => &[
                "struct Rgb",
                "struct Rgba",
                "struct CurvePoint",
                "struct Curve",
                "struct GradientStop",
                "struct Gradient",
            ],
            Lang::Lua => &[
                "@class Rgb",
                "@class Rgba",
                "@class CurvePoint",
                "@class Curve",
                "@class GradientStop",
                "@class Gradient",
            ],
        };
        for n in names {
            assert!(support.contains(n), "{lang:?}: bi_types lacks {n}\n{support}");
        }
        // Every type of the sample, and the ids the data gives.
        let (weapon, id) = match lang {
            Lang::C => ("struct Weapon {", "WEAPON_RUSTY_SWORD"),
            Lang::Cpp => ("struct Weapon {", "RUSTY_SWORD"),
            Lang::Go => ("type Weapon struct {", "WeaponRustySword"),
            Lang::Rust => ("pub struct Weapon {", "RUSTY_SWORD"),
            Lang::C3 => ("struct Weapon {", "WEAPON_RUSTY_SWORD"),
            Lang::Lua => ("@class Weapon", "rusty_sword"),
        };
        assert!(unit.contains(weapon), "{lang:?}\n{unit}");
        assert!(unit.contains(id), "{lang:?}: no id {id}\n{unit}");
        for t in ["Rarity", "Element", "Vec2", "Stats", "Enemy"] {
            assert!(unit.contains(t), "{lang:?}: no {t}");
        }
        // The pkg lands where the language has a place for it.
        match lang {
            Lang::Cpp => assert!(unit.contains("namespace gen::sample {")),
            Lang::Go => assert!(unit.contains("package sample\n")),
            Lang::C3 => assert!(unit.contains("module gen::sample;")),
            Lang::Lua => assert!(unit.contains("require(\"gen.sample.bi_types\")")),
            Lang::C | Lang::Rust => {
                assert!(out.notes.iter().any(|n| n.message.contains("--pkg has no effect")))
            }
        }
    }
}

#[test]
fn the_sample_mapping_changes_nothing() {
    for lang in Lang::ALL {
        let plain = generate(&request(lang, false), &mut no_read).unwrap();
        let mapped = generate(&request(lang, true), &mut no_read).unwrap();
        assert_eq!(plain.files, mapped.files, "{lang:?}");
    }
}

#[test]
fn the_output_is_deterministic() {
    for lang in Lang::ALL {
        let a = generate(&request(lang, true), &mut no_read).unwrap();
        let b = generate(&request(lang, true), &mut no_read).unwrap();
        assert_eq!(a.files, b.files, "{lang:?}");
    }
}
