//! `bi gen struct`: the schema's types, defaults and ids written as C,
//! C++, Go, Rust, C3 or Lua, steered by a `.bimapping`. A language-neutral
//! `Model` is built once — names cased and checked for the target,
//! defaults resolved, dependency order and boxed cycles found — and one
//! `Backend` per language turns each unit into text. Disk and prompts
//! are the caller's: `generate` takes text and hands back text, and
//! `write` asks through a trait. See `docs/specs/gen-struct.md`.

use std::path::{Path, PathBuf};

use crate::props::data::{self, DataFile};
use crate::props::schema::Schema;
use crate::props::{self, Diagnostic};

pub mod lang;
pub mod lit;
pub mod mapping;
pub mod model;
pub mod names;
pub mod write;

#[cfg(test)]
pub mod fixture;

pub use mapping::{External, Generics, LangMapping, Mapping};
pub use model::{
    Builtin, DataUnit, EnumValue, Field, Id, Instance, Model, Ty, Type, TypeKind, Unit,
};
pub use write::{Always, Ask, Fate, Overwrite, Report, write};

/// The stem of the support file, `bi_types.<ext>`, holding the colours,
/// the curve, the gradient and `Ref`.
pub const SUPPORT_STEM: &str = "bi_types";

/// The six targets. `name` is the TOML section key; the command line also
/// takes `c++`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Lang {
    C,
    Cpp,
    Go,
    Rust,
    C3,
    Lua,
}

impl Lang {
    pub const ALL: [Lang; 6] = [Lang::C, Lang::Cpp, Lang::Go, Lang::Rust, Lang::C3, Lang::Lua];

    pub fn parse(s: &str) -> Option<Lang> {
        Some(match s {
            "c" => Lang::C,
            "c++" | "cpp" => Lang::Cpp,
            "go" => Lang::Go,
            "rust" => Lang::Rust,
            "c3" => Lang::C3,
            "lua" => Lang::Lua,
            _ => return None,
        })
    }

    pub fn name(self) -> &'static str {
        match self {
            Lang::C => "c",
            Lang::Cpp => "cpp",
            Lang::Go => "go",
            Lang::Rust => "rust",
            Lang::C3 => "c3",
            Lang::Lua => "lua",
        }
    }

    pub fn ext(self) -> &'static str {
        match self {
            Lang::C => "h",
            Lang::Cpp => "hpp",
            Lang::Go => "go",
            Lang::Rust => "rs",
            Lang::C3 => "c3",
            Lang::Lua => "lua",
        }
    }

    /// The spellings the command line lists.
    pub const SPELLINGS: &'static str = "c, c++, go, rust, c3, lua";
}

/// What one run generates from.
#[derive(Debug, Clone, PartialEq)]
pub struct Request {
    pub lang: Lang,
    pub pkg: Option<String>,
    /// Path and text, in command-line order. Paths are what the data
    /// files' `$schema` resolve against.
    pub inputs: Vec<(PathBuf, String)>,
    pub mappings: Vec<(PathBuf, String)>,
    /// `-o`'s last component — Go's package when `--pkg` is not given.
    pub dir_name: String,
}

/// One generated file, its path relative to the output directory.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OutFile {
    pub path: PathBuf,
    pub text: String,
}

/// Everything a run produced: the files, and the notes and warnings that
/// did not stop it.
#[derive(Debug, Clone, PartialEq)]
pub struct Output {
    pub files: Vec<OutFile>,
    pub notes: Vec<Diagnostic>,
}

/// What a backend sees beside the model.
pub struct Context<'a> {
    pub pkg: Option<&'a str>,
    pub mapping: &'a LangMapping,
    pub dir_name: &'a str,
}

/// One language. `unit` writes one schema's file; `data` one data file's
/// instances, importing the unit; `support` the shared `bi_types` file,
/// `None` when no builtin is generated.
pub trait Backend {
    fn unit(&self, unit: &Unit, model: &Model, cx: &Context) -> String;
    fn data(&self, data: &DataUnit, unit: &Unit, model: &Model, cx: &Context) -> String;
    fn support(&self, model: &Model, cx: &Context) -> Option<String>;
}

/// The generated-by line every file opens with, after `comment`.
pub fn header(comment: &str, source: &str) -> String {
    format!("{comment} generated by `bi gen struct` from {source} — do not edit\n")
}

/// The whole run: mappings merged, inputs parsed into units, the model
/// built, every backend file rendered. `read` fetches a schema a data file
/// names that is not among the inputs.
pub fn generate(
    req: &Request,
    read: &mut dyn FnMut(&Path) -> Result<String, String>,
) -> Result<Output, Vec<Diagnostic>> {
    let mut errors = Vec::new();
    let mut notes = Vec::new();

    let mut mapping = Mapping::default();
    for (path, text) in &req.mappings {
        match Mapping::parse(text) {
            Ok(m) => mapping.merge(m),
            Err(e) => errors.extend(prefixed(path, e)),
        }
    }

    if let Some(pkg) = &req.pkg {
        if pkg.is_empty() || !pkg.split('.').all(props::is_identifier) {
            errors.push(Diagnostic::error(
                None,
                format!("--pkg {pkg}: every dot-separated segment must be an identifier"),
            ));
        } else if matches!(req.lang, Lang::C | Lang::Rust) {
            let how = match req.lang {
                Lang::Rust => {
                    "a module is its file — `mod <stem>;` and `mod bi_types;` go where the files went"
                }
                _ => "C has no namespaces — `prefix` in the mapping is the C way",
            };
            notes.push(Diagnostic::warning(
                None,
                format!("--pkg has no effect for {}: {how}", req.lang.name()),
            ));
        }
    }

    // Units keyed by the schema's normalised path, in first-seen order.
    let mut units: Vec<UnitIn> = Vec::new();
    let mut pending_data: Vec<(PathBuf, String, DataFile)> = Vec::new();
    for (path, text) in &req.inputs {
        match props::kind_of(path) {
            Some(props::Kind::Schema) => match Schema::parse(text) {
                Ok((_, schema)) => {
                    let key = normalize(path);
                    if !units.iter().any(|u| u.key == key) {
                        units.push(UnitIn { key, path: path.clone(), schema, data: Vec::new() });
                    }
                }
                Err(e) => errors.extend(prefixed(path, e)),
            },
            Some(props::Kind::Data) => match data::parse(text) {
                Ok((_, df)) => pending_data.push((path.clone(), text.clone(), df)),
                Err(e) => errors.extend(prefixed(path, e)),
            },
            _ => errors.push(Diagnostic::error(
                None,
                format!("{}: not a .bischema or .bidata", path.display()),
            )),
        }
    }
    for (path, text, df) in pending_data {
        let Some(schema_path) = data::schema_path(&path, &df.schema) else {
            errors.push(Diagnostic::error(
                None,
                format!("{}: $schema {} has no directory", path.display(), df.schema),
            ));
            continue;
        };
        let key = normalize(&schema_path);
        if !units.iter().any(|u| u.key == key) {
            match read(&schema_path) {
                Ok(schema_text) => match Schema::parse(&schema_text) {
                    Ok((_, schema)) => units.push(UnitIn {
                        key: key.clone(),
                        path: schema_path.clone(),
                        schema,
                        data: Vec::new(),
                    }),
                    Err(e) => {
                        errors.extend(prefixed(&schema_path, e));
                        continue;
                    }
                },
                Err(why) => {
                    errors.push(Diagnostic::error(
                        None,
                        format!("{}: schema {} — {why}", path.display(), schema_path.display()),
                    ));
                    continue;
                }
            }
        }
        let unit = units.iter_mut().find(|u| u.key == key).expect("just inserted");
        unit.data.push((path, text, df));
    }

    // Data checked against its schema, with the other data files of the
    // unit as the index: errors stop, warnings ride along.
    for unit in &units {
        for (i, (path, _, df)) in unit.data.iter().enumerate() {
            let others: Vec<(PathBuf, String)> = unit
                .data
                .iter()
                .enumerate()
                .filter(|(j, _)| *j != i)
                .map(|(_, (p, t, _))| (p.clone(), t.clone()))
                .collect();
            let index = data::Index::build(&others);
            for d in data::validate(df, &unit.schema, &index) {
                let d = Diagnostic { message: format!("{}: {}", path.display(), d.message), ..d };
                match d.level {
                    props::Level::Error => errors.push(d),
                    props::Level::Warning => notes.push(d),
                }
            }
        }
    }

    // Stems: one file each — schemas and, when instances are generated,
    // data files — none the support file's.
    let mut stems: Vec<(String, PathBuf)> = Vec::new();
    let mut claim = |path: &Path, what: &str, errors: &mut Vec<Diagnostic>| -> String {
        let stem = path.file_stem().map(|s| s.to_string_lossy().into_owned()).unwrap_or_default();
        if stem == SUPPORT_STEM {
            errors.push(Diagnostic::error(
                None,
                format!(
                    "{}: `{SUPPORT_STEM}` is the support file's name — rename the {what}",
                    path.display()
                ),
            ));
        }
        if let Some((_, other)) = stems.iter().find(|(s, _)| *s == stem) {
            errors.push(Diagnostic::error(
                None,
                format!(
                    "{} and {} both write {stem}.{}",
                    other.display(),
                    path.display(),
                    req.lang.ext()
                ),
            ));
        }
        stems.push((stem.clone(), path.to_path_buf()));
        stem
    };
    let mut unit_stems = Vec::new();
    let mut data_stems: Vec<Vec<String>> = Vec::new();
    for unit in &units {
        unit_stems.push(claim(&unit.path, "schema", &mut errors));
        let mut ds = Vec::new();
        for (path, _, _) in &unit.data {
            ds.push(if mapping.instances {
                claim(path, "data file", &mut errors)
            } else {
                String::new()
            });
        }
        data_stems.push(ds);
    }
    if !errors.is_empty() {
        return Err(errors);
    }

    let lang_mapping = mapping.for_lang(req.lang);
    let name_of = |p: &Path, stem: &str| {
        p.file_name().map(|s| s.to_string_lossy().into_owned()).unwrap_or(stem.to_string())
    };
    let built: Vec<(String, String, Schema, Vec<(String, String, DataFile)>)> = units
        .into_iter()
        .zip(unit_stems)
        .zip(data_stems)
        .map(|((u, stem), ds)| {
            let source = name_of(&u.path, &stem);
            let data = u
                .data
                .into_iter()
                .zip(ds)
                .map(|((p, _, d), dstem)| (dstem.clone(), name_of(&p, &dstem), d))
                .collect();
            (stem, source, u.schema, data)
        })
        .collect();
    let (model, model_notes) =
        Model::build(req.lang, built, &lang_mapping, mapping.ids, mapping.instances)?;
    notes.extend(model_notes);

    let backend = lang::backend_for(req.lang);
    let cx = Context { pkg: req.pkg.as_deref(), mapping: &lang_mapping, dir_name: &req.dir_name };
    let mut files = Vec::new();
    for unit in &model.units {
        files.push(OutFile {
            path: PathBuf::from(format!("{}.{}", unit.stem, req.lang.ext())),
            text: backend.unit(unit, &model, &cx),
        });
        for d in &unit.data {
            files.push(OutFile {
                path: PathBuf::from(format!("{}.{}", d.stem, req.lang.ext())),
                text: backend.data(d, unit, &model, &cx),
            });
        }
    }
    if let Some(text) = backend.support(&model, &cx) {
        files.push(OutFile {
            path: PathBuf::from(format!("{SUPPORT_STEM}.{}", req.lang.ext())),
            text,
        });
    }
    Ok(Output { files, notes })
}

/// A schema on its way to becoming a unit.
struct UnitIn {
    key: PathBuf,
    path: PathBuf,
    schema: Schema,
    data: Vec<(PathBuf, String, DataFile)>,
}

fn prefixed(path: &Path, diagnostics: Vec<Diagnostic>) -> Vec<Diagnostic> {
    diagnostics
        .into_iter()
        .map(|d| Diagnostic { message: format!("{}: {}", path.display(), d.message), ..d })
        .collect()
}

/// `a/./b/../c` and `a/c` are one path: the same schema reached two ways
/// counts once. No disk — two spellings of one file through a symlink
/// are the caller's to canonicalise.
pub fn normalize(path: &Path) -> PathBuf {
    use std::path::Component;
    let mut out = PathBuf::new();
    for c in path.components() {
        match c {
            Component::CurDir => {}
            Component::ParentDir => {
                if !out.pop() {
                    out.push("..");
                }
            }
            other => out.push(other.as_os_str()),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lang_parses_every_spelling() {
        assert_eq!(Lang::parse("c++"), Some(Lang::Cpp));
        assert_eq!(Lang::parse("cpp"), Some(Lang::Cpp));
        assert_eq!(Lang::parse("Rust"), None);
        for l in Lang::ALL {
            assert_eq!(Lang::parse(l.name()), Some(l));
        }
        assert_eq!(Lang::Cpp.ext(), "hpp");
        assert_eq!(
            header("//", "game.bischema"),
            "// generated by `bi gen struct` from game.bischema — do not edit\n"
        );
    }

    fn req(lang: Lang, inputs: &[(&str, &str)], mappings: &[&str], pkg: Option<&str>) -> Request {
        Request {
            lang,
            pkg: pkg.map(str::to_string),
            inputs: inputs.iter().map(|(p, t)| (PathBuf::from(p), t.to_string())).collect(),
            mappings: mappings
                .iter()
                .enumerate()
                .map(|(i, t)| (PathBuf::from(format!("m{i}.bimapping")), t.to_string()))
                .collect(),
            dir_name: "out".into(),
        }
    }

    fn no_read(p: &Path) -> Result<String, String> {
        Err(format!("unexpected read of {}", p.display()))
    }

    #[test]
    fn a_schema_makes_its_file_and_the_support_file() {
        let out = generate(
            &req(Lang::Rust, &[("weapons.bischema", fixture::SCHEMA)], &[], None),
            &mut no_read,
        )
        .unwrap();
        let paths: Vec<String> = out.files.iter().map(|f| f.path.display().to_string()).collect();
        assert_eq!(paths, ["weapons.rs", "bi_types.rs"]);
        assert!(
            out.files[0].text.starts_with(
                "// generated by `bi gen struct` from weapons.bischema — do not edit\n"
            )
        );
        assert!(out.notes.is_empty());
    }

    #[test]
    fn a_data_file_brings_its_schema_through_read() {
        let mut reads = Vec::new();
        let mut read = |p: &Path| {
            reads.push(p.to_path_buf());
            if p == Path::new("data/weapons.bischema") {
                Ok(fixture::SCHEMA.to_string())
            } else {
                Err("no".into())
            }
        };
        let out = generate(
            &req(Lang::Rust, &[("data/level1.bidata", fixture::DATA)], &[], None),
            &mut read,
        )
        .unwrap();
        assert_eq!(reads, [PathBuf::from("data/weapons.bischema")]);
        assert_eq!(out.files[0].path, PathBuf::from("weapons.rs"));
        assert!(out.files[0].text.contains("RUSTY_SWORD"), "ids from the data");

        // The schema given too, by another spelling: still one unit, no read.
        let out = generate(
            &req(
                Lang::Rust,
                &[
                    ("data/../data/./weapons.bischema", fixture::SCHEMA),
                    ("data/level1.bidata", fixture::DATA),
                ],
                &[],
                None,
            ),
            &mut no_read,
        )
        .unwrap();
        assert_eq!(out.files.len(), 3, "the schema's, the data file's, the support file");
    }

    #[test]
    fn refusals_name_the_file() {
        let e = generate(
            &req(Lang::Rust, &[("level1.bidata", fixture::DATA)], &[], None),
            &mut no_read,
        )
        .unwrap_err();
        assert!(
            e[0].message.starts_with("level1.bidata: schema weapons.bischema — "),
            "{}",
            e[0].message
        );
        let e = generate(
            &req(
                Lang::Go,
                &[("a/game.bischema", fixture::SCHEMA), ("b/game.bischema", fixture::CYCLE)],
                &[],
                None,
            ),
            &mut no_read,
        )
        .unwrap_err();
        assert_eq!(e[0].message, "a/game.bischema and b/game.bischema both write game.go");
        let e = generate(
            &req(
                Lang::Go,
                &[("weapons.bischema", fixture::SCHEMA), ("weapons.bidata", fixture::DATA)],
                &[],
                None,
            ),
            &mut no_read,
        )
        .unwrap_err();
        assert_eq!(e[0].message, "weapons.bischema and weapons.bidata both write weapons.go");
        assert!(
            generate(
                &req(
                    Lang::Go,
                    &[("weapons.bischema", fixture::SCHEMA), ("weapons.bidata", fixture::DATA)],
                    &["instances = false\n"],
                    None
                ),
                &mut no_read,
            )
            .is_ok(),
            "no data file written, no clash"
        );
        let e = generate(
            &req(Lang::Go, &[("bi_types.bischema", fixture::SCHEMA)], &[], None),
            &mut no_read,
        )
        .unwrap_err();
        assert!(e[0].message.contains("`bi_types` is the support file's name"));
        let e = generate(
            &req(Lang::Go, &[("g.bischema", fixture::SCHEMA)], &[], Some("gen.2d")),
            &mut no_read,
        )
        .unwrap_err();
        assert_eq!(e[0].message, "--pkg gen.2d: every dot-separated segment must be an identifier");
        let e =
            generate(&req(Lang::Go, &[("g.bischema", "{")], &[], None), &mut no_read).unwrap_err();
        assert!(e[0].message.starts_with("g.bischema: invalid JSON"));
        let e = generate(
            &req(Lang::Go, &[("g.bischema", fixture::SCHEMA)], &["[java]\n"], None),
            &mut no_read,
        )
        .unwrap_err();
        assert!(e[0].message.starts_with("m0.bimapping: line 1: unknown language"));
        let e = generate(&req(Lang::Go, &[("g.txt", "")], &[], None), &mut no_read).unwrap_err();
        assert_eq!(e[0].message, "g.txt: not a .bischema or .bidata");
    }

    #[test]
    fn data_is_validated_and_warnings_ride_along() {
        let bad = fixture::DATA.replace(
            "\"owner\": \"rusty_sword\" }",
            "\"owner\": \"rusty_sword\", \"damage\": \"x\" }",
        );
        let e = generate(
            &req(
                Lang::Rust,
                &[("weapons.bischema", fixture::SCHEMA), ("level1.bidata", &bad)],
                &[],
                None,
            ),
            &mut no_read,
        )
        .unwrap_err();
        assert!(e[0].message.starts_with("level1.bidata: "), "{}", e[0].message);
        let dangling =
            fixture::DATA.replace("\"owner\": \"rusty_sword\" }", "\"owner\": \"nope\" }");
        let out = generate(
            &req(
                Lang::Rust,
                &[("weapons.bischema", fixture::SCHEMA), ("level1.bidata", &dangling)],
                &[],
                None,
            ),
            &mut no_read,
        )
        .unwrap();
        assert!(
            out.notes
                .iter()
                .any(|n| n.message.starts_with("level1.bidata: ") && n.message.contains("nope")),
            "{:?}",
            out.notes
        );
    }

    #[test]
    fn pkg_notes_for_the_languages_without_one() {
        let out = generate(
            &req(Lang::Rust, &[("g.bischema", fixture::SCHEMA)], &[], Some("gen.so")),
            &mut no_read,
        )
        .unwrap();
        assert_eq!(
            out.notes[0].message,
            "--pkg has no effect for rust: a module is its file — `mod <stem>;` and `mod bi_types;` go where the files went"
        );
        let out = generate(
            &req(Lang::Cpp, &[("g.bischema", fixture::SCHEMA)], &[], Some("gen.so")),
            &mut no_read,
        )
        .unwrap();
        assert!(out.notes.is_empty());
    }

    #[test]
    fn normalize_folds_dots() {
        assert_eq!(normalize(Path::new("a/./b/../c.bischema")), PathBuf::from("a/c.bischema"));
        assert_eq!(normalize(Path::new("../x")), PathBuf::from("../x"));
    }
}
